const businessCategories = [
    { value: 'supermarket', label: 'Supermarket' },
    { value: 'restaurant', label: 'Restaurant' },
    { value: 'catering_service', label: 'Catering Service' },
    { value: 'food_delivery', label: 'Food Delivery' },
    { value: 'bakery', label: 'Bakery' },
    { value: 'beverage_supplier', label: 'Beverage Supplier' },
    { value: 'farmers_market', label: 'Farmers Market' },
    { value: 'food_truck', label: 'Food Truck' },
    { value: 'grocery_store', label: 'Grocery Store' },
    { value: 'organic_food_store', label: 'Organic Food Store' },
    { value: 'convenience_store', label: 'Convenience Store' },
    { value: 'butcher', label: 'Butcher' },
    { value: 'fishmonger', label: 'Fishmonger' },
    { value: 'dairy_shop', label: 'Dairy Shop' },
    { value: 'produce_stand', label: 'Produce Stand' },
    { value: 'frozen_food_supplier', label: 'Frozen Food Supplier' },
    { value: 'clothing_store', label: 'Clothing Store' },
    { value: 'electronics_store', label: 'Electronics Store' },
    { value: 'furniture_store', label: 'Furniture Store' },
    { value: 'bookstore', label: 'Bookstore' },
    { value: 'toy_store', label: 'Toy Store' },
    { value: 'hardware_store', label: 'Hardware Store' },
    { value: 'pharmacy', label: 'Pharmacy' },
    { value: 'sporting_goods_store', label: 'Sporting Goods Store' },
    { value: 'office_supplies_store', label: 'Office Supplies Store' },
    { value: 'appliance_store', label: 'Appliance Store' },
    { value: 'stationery_store', label: 'Stationery Store' },
    { value: 'secondhand_store', label: 'Secondhand Store' },
];

export default businessCategories;
