const countyData =  [
    "Marsabit County",
    "Mandera County",
    "Kitui County",
    "Bungoma County",
    "Vihiga County",
    "Trans Nzoia County",
    "Nakuru County",
    "Nyeri County",
    "Garissa County",
    "Nyandarua County",
    "Lamu County",
    "Laikipia County",
    "Tharaka Nithi County",
    "Nandi County",
    "Embu County",
    "Elgeyo Marakwet County",
    "Kirinyaga County",
    "Baringo County",
    "Samburu County",
    "Meru County",
    "Isiolo County",
    "Kisii County",
    "Kwale County",
    "Muranga County",
    "Machakos County",
    "Wajir County",
    "Homa Bay County",
    "West Pokot County",
    "Kisumu County",
    "Kericho County",
    "Kajiado County",
    "Bomet County",
    "Kakamega County",
    "Busia County",
    "Makueni County",
    "Uasin Gishu County",
    "Migori County",
    "Kiambu County",
    "Nyamira County",
    "Tana River County",
    "Kilifi County",
    "Taita Taveta County",
    "Turkana County",
    "Nairobi County",
    "Narok County",
    "Siaya County",
    "Mombasa County"
  ];

export  default countyData;

